config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

    resources :restaurants, only: [:new, :show, :edit, :index,:create] do
      resources :reservations, only: [:new, :show, :edit, :index, :create]
       resources :reviews
    end
    resources :sessions, only:[:new,:create,:destroy]

    resources :users, only: [:new, :show, :edit, :create]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  def formatted_time
     self.time.strftime("%A, %m/%d at %I:%M %p, %Y")
   end

  #  validates :party_size, presence: true, numericality: {only_integer: true, greater_than: 2}
   validates :time, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  has_many :reviews
  has_many :users, through: :reviews

  def available?(party_size,time)
     available_capacity = capacity - reservations.where('time >= ? and time < ?', time.beginning_of_hour, time.end_of_hour).sum(:party_size)
     party_size > 0 && party_size <= available_capacity

  end







end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true , uniqueness: true


  has_many :restaurants, through: :reservations
  has_many :reservations
  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
private
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end

   def ensure_logged_in
      unless current_user
        flash[:alert] = "Please log in"
        redirect_to new_session_path
      end
   end

 helper_method :current_user

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_filter :load_parent
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end



  def create
   @reservation = Reservation.new(reservation_params)
   @reservation.user = current_user
   @reservation.restaurant_id = @restaurant.id


   if @restaurant.available?(@reservation.party_size, @reservation.time)
      @restaurant.capacity = @restaurant.capacity -= @reservation.party_size
     @restaurant.save
     
     @reservation.save
     redirect_to restaurant_path(@restaurant), notice: "Your reservation was created successfully"
   else
      render 'restaurants/show'
   end
 end


  def show
    @reservation = Reservation.find(params[:id])

  end

  def edit
    @reservation = Reservation.find(params[:id])

  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
     redirect_to reservation_path(@reservation)
   else
     render 'edit'
   end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to restaurants_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:time, :party_size)

  end

  def load_parent

    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save

      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end


  def update
    @restaurant = Restaurant.find(params[:id])
      if @restaurant.update_attributes(restaurant_params)
        redirect_to restaurant_path(@restaurant)
      else
        #when we add ui then put in flash notice
        render 'edit'
      end
    
  end

  def show
    @restaurant = Restaurant.find(params[:id])


    @reservation = @restaurant.reservations.build
    @review = @restaurant.reviews.build

  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path

  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :capacity, :photo)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 before_filter :ensure_logged_in, only: [:create, :destroy]
 before_filter :load_parent

 def show
   @review = Review.find(params[:id])
 end

 def create
   @review = @restaurant.reviews.build(review_params)
   @review.user = current_user

   if @review.save
     redirect_to restaurants_path, notice: 'Review created successfully'
   else
     render 'restaurant_path(@restaurant)'
   end
 end

 def destroy
   @review = Review.find(params[:id])
   @review.destroy
   redirect_to restaurants_path
 end

 def edit
   @review = Review.find(params[:id])
 end

 def update
   @review = Review.find(params[:id])
       if @review.update_attributes(review_params)
         redirect_to restaurants_path
       else
         #when we add ui then put in flash notice
         render 'edit'
       end

   end

 private

   def review_params
     params.require(:review).permit(:comment, :restaurant_id)
   end

   def load_parent
     @restaurant = Restaurant.find(params[:restaurant_id])
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

      def new
      end
      
    def create
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: "Logged in!"
      else
        flash.now[:alert] = "Invalid email or password"
        render 'new'
      end

    end

    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_path, notice: "Signed up!"
    else
      render 'new'
    end
  end

  def edit
      @user = User.find(params[:id])

  end

  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to user_path(@user)
      else
        render 'edit'
      end
  end

  # def destroy
  #     @user = User.find(params[:id])
  #     @user.destroy
  #     redirect_to restaurants_path
  #
  # end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<% if current_user %>
  <%= render '/layouts/nav_user' %>
<% else %>
  <%= render '/layouts/nav_guest' %>
<%end %>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Seat Yourself</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to'All restaurants', root_path %></li>







        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Log in', new_session_path)%></li>
        <li><%= link_to('Sign up', new_user_path)%></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Seat Yourself</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
            <li><%= link_to'All restaurants', root_path %></li>
            <li><%= link_to'Profile', user_path(current_user)%></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Log out', session_path("current"), :method => :delete %></li>
      <li><a> Welcome <%=current_user.name.capitalize %>!</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render '/layouts/nav' %>

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>
<%= yield %>



</body>
</html>

app/views/reservations/_form.html.erb
<div class="col-xs-4 col-xs-offset-4">

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Review</h3>
  </div>
  <div class="panel-body">
    <%= form_for([@restaurant, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

          <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

  </div>
</div>
</div>

app/views/reservations/edit.html.erb
<h1>Edit Your Reservation</h1>
<%= render 'form' %>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>
<%= current_user.reservations.all %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |i| %>

  <div class="field">
    <%= i.label :name %><br/>
    <%= i.text_field :name %>
  </div>

  <div class="field">
    <%= i.label :capacity %><br/>
    <%= i.number_field :capacity %>
  </div>

  <div class="field">
    <%= i.label :photo %><br/>
    <%= i.text_field :photo %>
  </div>


  <div class="action">
    <%= i.submit "Create Restaurant" %>
  </div>

 <% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant </h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="home-wrapper">
<div class="container">

  <div class="row" >
    <div class="col-xs-12">
   <h1 id="restaurant-header">RESTAURANTS</h1>
    <h4 id="restaurant-header">There are currently <%= pluralize(Restaurant.all.length,'restaurant') %> listed</h4>
  </div>
</div>


  <% @restaurants.each do |restaurant| %>
  <div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
        <h3  class="panel-title" > <h2 > <%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h2></h3>
        </div>
        <div class="panel-body"class="img-responsive">
            <p ><%= image_tag restaurant.photo, {size: "320"} %></p>
            <div class="col-xs-4">
                <p> Capacity: <%= restaurant.capacity %> </p><br/>

            </div>
                <div class="col-xs-4 col-sm-offset-2" >
              <%= link_to '<button type="button" class="btn btn-danger">Book Reservation</button>'.html_safe ,restaurant_path(restaurant) %>

            </div>
        </div>
    </div>
  </div>

  <% end %>


</div>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant </h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<% if @reservation.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this product from being saved:</h2>

     <ul>
     <% @reservation.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<div class="col-xs-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Reservation Info </h3>
    </div>
    <div class="panel-body">
      <% if current_user %>

      <%= form_for ([@restaurant, @reservation]) do |i| %>

        <div class="field">
          <%= i.label :time %><br/>
          <%= i.datetime_local_field :time %>
        </div>

        <div class="field">
          <%= i.label :party_size %><br/>
          <%= i.number_field :party_size %>
        </div>

        <div class="action">
          <%= i.submit "Create Reservation" %>

        </div>




       <% end %>

       <% else %>
         <p>Please log in to create a reservation</p>
         <% end %>

    </div>
  </div>
</div>

<div class="col-xs-5">
  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @restaurant.name %></h3>
  </div>
  <div class="panel-body">

    <p><%= image_tag @restaurant.photo, {size: "400"} %></p>

    <p>Available capacity:<p> <%= @restaurant.capacity %>

  </div>
</div>
</div>


<div class="col-xs-3">
  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @restaurant.name %></h3>
  </div>
  <div class="panel-body">


<h4>Reviews for <%= @restaurant.name %></h4>

<% @restaurant.reviews.order(created_at: :desc).each do |review| %>
 <p>
   <%= review.comment %>
   <br>
   <% if review.user != nil %>
     <em> by <%= review.user.email %></em>
     Added on: <%= review.created_at %>
   <% end %>
 </p>
<% end %>

<% if current_user %>
 <h4>New review</h4>

 <%= form_for([@restaurant, @review]) do |f| %>
   <% if @review.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

       <ul>
       <% @review.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

   <div class="field">
     <%= f.label :comment %><br />
     <%= f.text_area :comment %>
   </div>
   <div class="actions">
     <%= f.submit %>
   </div>
 <% end %>

<% else %>
 <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>



  </div>
</div>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |i| %>

  <div class="field">
    <%= i.label :name %><br/>
    <%= i.text_field :name %>
  </div>

  <div class="field">
    <%= i.label :email %><br/>
    <%= i.email_field :email %>
  </div>

  <div class="field">
    <%= i.label :password %><br/>
    <%= i.password_field :password %>
  </div>

  <div class="field">
    <%= i.label :password_confirmation %><br/>
    <%= i.password_field :password_confirmation %>
  </div>

  <div class="action">
    <%= i.submit "Create Account" %>
  </div>

 <% end %>

app/views/users/edit.html.erb
<h1>edit user </h1>
<%= render 'form' %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-4">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Sign up</h3>
  </div>
  <div class="panel-body">
  <%= render 'form' %>

  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-body">
              Username: <%= @user.name %></BR>
              Email: <%= @user.email %>
          </div>
      </div>
    </div>

  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1>RESERVATIONS</h1>
        <% @user.reservations.order(created_at: :desc).each do |x|  %>
          <ul>
            <li>Restaurant name: <%= x.restaurant.name %></li>
                Booking : <%= x.formatted_time %></br>
                Party Size: <%= x.party_size %></br>
          </ul>
        <% end %>
      </div>
  </div>
</div>


<div class="col-xs-4">
  <div class="panel panel-default">
    <div class="panel-body">
      <h1> <%= pluralize(@user.reviews.count ,'review') %> from <%= @user.name %> </h1>
        <% @user.reviews.order(created_at: :desc).each do |review| %>
        <ul>
          <li><em>Review for restaurant: </em><%= review.restaurant.name %></li>
          <em>Review comment: </em> <%= review.comment %></br>
          <%= link_to 'edit comment', edit_restaurant_review_path(review.restaurant_id, review.id) %></br>
          <%= link_to 'delete comment', restaurant_review_url( review.restaurant_id, review.id ) , method: :delete, data:{confirm:"are you sure you want to delete this review"} %>
        </ul>
        <% end %>
    </div>
</div>
</div>



  </div>
</div>